version: 2
updates:
- package-ecosystem: nuget
  directory: "/dashboard/src/Piipan.Dashboard"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/dashboard/tests/Piipan.Dashboard.Tests"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/etl/src/Piipan.Etl"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/etl/tests/Piipan.Etl.Tests"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/match/src/Piipan.Match.State"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/match/src/Piipan.Match.Orchestrator"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/match/tests/Piipan.Match.State.Tests"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/match/tests/Piipan.Match.State.IntegrationTests"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/match/tests/Piipan.Match.Orchestrator.Tests"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/metrics/src/Piipan.Metrics/Piipan.Metrics.Api"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/metrics/src/Piipan.Metrics/Piipan.Metrics.Collect"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/metrics/src/Piipan.Metrics/Piipan.Metrics.Models"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/metrics/tests/Piipan.Metrics.Tests"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/shared/src/Piipan.Shared"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/shared/tests/Piipan.Shared.Tests"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/query-tool/src/Piipan.QueryTool"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: nuget
  directory: "/query-tool/tests/Piipan.QueryTool.Tests"
  schedule:
    interval: daily
    time: "09:00"
