openapi: 3.0.0
info:
  title: Bulk API
  version: 2.0.0
  description: The API for performing bulk uploads
tags:
  - name: Upload
servers:
  - url: '/bulk/{stateAbbr}/v2'
    variables:
      stateAbbr:
        default: none
        description: Lowercase two-letter postal code abbreviation
paths:
  '/upload/{filename}':
    put:
      operationId: Upload a File
      summary: Upload a CSV file of bulk participant data
      tags:
        - Upload
      parameters:
        - name: filename
          in: path
          description: Name of file being uploaded
          required: true
          schema:
            type: string
        - in: header
          name: Content-Length
          schema:
            type: integer
          required: true
          description: Size in bytes of your file to be uploaded. A curl request will add this header by default when including a data or file parameter.
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: File uploaded
        '401':
          description: Access denied
        '411':
          description: Content-Length not provided
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Ocp-Apim-Subscription-Key
